export const CHECK_NODE_STATUS_START = "CHECK_NODE_STATUS_START";
export const CHECK_NODE_STATUS_SUCCESS = "CHECK_NODE_STATUS_SUCCESS";
export const CHECK_NODE_STATUS_FAILURE = "CHECK_NODE_STATUS_FAILURE";

export const BLOCKS_STATUS_FAILURE = "BLOCKS_STATUS_FAILURE";
export const BLOCKS_STATUS_SUCCESS = "BLOCKS_STATUS_SUCCESS";
export const BLOCKS_STATUS_START = "BLOCKS_STATUS_START";
